### ISSUE TITLE
Boundary condition

### ISSUE THREAD

**Issue by kaushikb258** [AbhilashReddyM/GeometricMultigrid#2]
Nice work! I think you are applying Dirichlet boundary condition in the FMG function. Is there a way to apply Neumann boundary condition, du/dx = 0 at left/right and du/dy = 0 at top/bottom?

**Comment by AbhilashReddyM** [comment]
@kaushikb258 Hey there! Thank you. You are correct. The boundary conditions are hard coded for homogeneous Dirichlet conditions on all boundaries.
In the 2d code, changing the boundary condition statements from
```python
  u[ 0,:] = -u[ 1,:]
  u[-1,:] = -u[-2,:]
  u[:, 0] = -u[:, 1]
  u[:,-1] = -u[:,-2]
```
to
```python
  u[ 0,:] = u[ 1,:]
  u[-1,:] = u[-2,:]
  u[:, 0] = u[:, 1]
  u[:,-1] = u[:,-2]
```
in the three places in the function `Jacrelax()` will apply homogeneous Neumann BCs on all boundaries. I have tested it on a corresponding sample problem and it does work. The modified code is attached. (Note that when you have all Neumann BCs the solution is only determined upto a constant)
[example_FMG_neumann.zip](https://github.com/AbhilashReddyM/GeometricMultigrid/files/5090870/example_FMG_neumann.zip)

**Comment by kaushikb258** [comment]
Thank you for the prompt response and help! I will run the new code.
